kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
     name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-identity-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-browsing-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-users-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-review-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-watching-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 4Gi