# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '70b2d43c-0211-4032-a9bd-757315ae0b9e'
  imageRepository: 'seriestracker'
  containerRegistry: 'seriestrackeracr.azurecr.io'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students (8445a3a1-9b69-45a5-8c09-9e1e6ebe6617)'
        azureContainerRegistry: '{"loginServer":"seriestrackeracr.azurecr.io", "id" : "/subscriptions/8445a3a1-9b69-45a5-8c09-9e1e6ebe6617/resourceGroups/series_tracker/providers/Microsoft.ContainerRegistry/registries/seriestrackerAcr"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'
    
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure for Students (8445a3a1-9b69-45a5-8c09-9e1e6ebe6617)'
        azureContainerRegistry: '{"loginServer":"seriestrackeracr.azurecr.io", "id" : "/subscriptions/8445a3a1-9b69-45a5-8c09-9e1e6ebe6617/resourceGroups/series_tracker/providers/Microsoft.ContainerRegistry/registries/seriestrackerAcr"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        additionalImageTags: 'v1'
      
    - task: DockerCompose@0
      inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'Azure for Students (8445a3a1-9b69-45a5-8c09-9e1e6ebe6617)'
          azureContainerRegistry: '{"loginServer":"seriestrackeracr.azurecr.io", "id" : "/subscriptions/8445a3a1-9b69-45a5-8c09-9e1e6ebe6617/resourceGroups/series_tracker/providers/Microsoft.ContainerRegistry/registries/seriestrackerAcr"}'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Push services'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'seriestracker_build'
        publishLocation: 'Container'
