# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '70b2d43c-0211-4032-a9bd-757315ae0b9e'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Ingyenes próba(a941a661-3ebd-4b58-904a-e5d52e6538c4)'
        azureContainerRegistry: '{"loginServer":"seriestrackerapp.azurecr.io", "id" : "/subscriptions/a941a661-3ebd-4b58-904a-e5d52e6538c4/resourceGroups/seriestracker/providers/Microsoft.ContainerRegistry/registries/seriestrackerapp"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'
        
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Ingyenes próba(a941a661-3ebd-4b58-904a-e5d52e6538c4)'
        azureContainerRegistry: '{"loginServer":"seriestrackerapp.azurecr.io", "id" : "/subscriptions/a941a661-3ebd-4b58-904a-e5d52e6538c4/resourceGroups/seriestracker/providers/Microsoft.ContainerRegistry/registries/seriestrackerapp"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        additionalImageTags: 'v1'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          export id=$(docker images --filter "label=test=true" -q | head -1)
              docker create --name testcontainer $id
              docker cp testcontainer:/testresults ./testresults
              docker rm testcontainer
              ls ./testresults
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*tests.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/testresults'
    
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/testresults/coverage/coverage.cobertura.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/testresults/reports'
      
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Ingyenes próba(a941a661-3ebd-4b58-904a-e5d52e6538c4)'
        azureContainerRegistry: '{"loginServer":"seriestrackerapp.azurecr.io", "id" : "/subscriptions/a941a661-3ebd-4b58-904a-e5d52e6538c4/resourceGroups/seriestracker/providers/Microsoft.ContainerRegistry/registries/seriestrackerapp"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'Kubernetes'
        ArtifactName: 'helm_charts'
        publishLocation: 'Container'

