version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - seriestracker-network
    

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    environment:
      - ApplicationInsights__InstrumentationKey=${ApplicationInsightsInstrumentationKey}
    networks:
      - seriestracker-network

  profileservice:
    image: ${DOCKER_REGISTRY-}profileservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    networks:
      - seriestracker-network

  reviewservice:
    image: ${DOCKER_REGISTRY-}reviewservice
    build:
      context: .
      dockerfile: ReviewService/Dockerfile
    networks:
      - seriestracker-network

  watchingservice:
    image: ${DOCKER_REGISTRY-}watchingservice
    build:
      context: .
      dockerfile: WatchingService/Dockerfile
    networks:
      - seriestracker-network
    
  browsingservice:
    image: ${DOCKER_REGISTRY-}browsingservice
    build:
      context: .
      dockerfile: BrowsingService/Dockerfile
    networks:
      - seriestracker-network

networks:
  seriestracker-network:
    driver: bridge