apiVersion: v1
kind: ConfigMap
metadata:
  name: browsing-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:seriestracker-browsingdb.database.windows.net,1433;Initial Catalog=BrowsingDb;Persist Security Info=False;User ID=dbLogin;Password=BigPassw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672,
            "Password": "Str0ngRabbitPass"
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:seriestracker-identitydb.database.windows.net,1433;Initial Catalog=IdentityDb;Persist Security Info=False;User ID=dbLogin;Password=BigPassw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672,
            "Password": "Str0ngRabbitPass"
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "Server=tcp:seriestracker-usersdb.database.windows.net,1433;Initial Catalog=UsersDb;Persist Security Info=False;User ID=dbLogin;Password=BigPassw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672,
            "Password": "Str0ngRabbitPass"
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: review-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:seriestracker-reviewdb.database.windows.net,1433;Initial Catalog=ReviewDb;Persist Security Info=False;User ID=dbLogin;Password=BigPassw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672,
            "Password": "Str0ngRabbitPass"
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: watching-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:seriestracker-watchingdb.database.windows.net,1433;Initial Catalog=WatchingDb;Persist Security Info=False;User ID=dbLogin;Password=BigPassw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672,
            "Password": "Str0ngRabbitPass"
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  ocelot.json: |-
    {
      "ReRoutes": [
        {
          "DownstreamPathTemplate": "/api/series/{everything}",
          "DownstreamScheme": "http",
          "ServiceName": "browsing-service",
          "UpstreamPathTemplate": "/series/{everything}",
          "UpstreamHttpMethod": [ "Get" ]
        },

        {
          "DownstreamPathTemplate": "/api/series",
          "DownstreamScheme": "http",
          "ServiceName": "browsing-service",
          "UpstreamPathTemplate": "/series",
          "UpstreamHttpMethod": [ "Get" ]
        },

        {
          "DownstreamPathTemplate": "/api/artist/{everything}",
          "DownstreamScheme": "http",
          "ServiceName": "browsing-service",
          "UpstreamPathTemplate": "/artist/{everything}",
          "UpstreamHttpMethod": [ "Get" ]
        },

        {
          "DownstreamPathTemplate": "/api/artist",
          "DownstreamScheme": "http",
          "ServiceName": "browsing-service",
          "UpstreamPathTemplate": "/artist",
          "UpstreamHttpMethod": [ "Get" ]
        },

        {
          "DownstreamPathTemplate": "/api/watching/{everything}",
          "DownstreamScheme": "http",
          "ServiceName": "watching-service",
          "UpstreamPathTemplate": "/watching/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ]
        },

        {
          "DownstreamPathTemplate": "/api/review/{everything}",
          "DownstreamScheme": "http",
          "ServiceName": "review-service",
          "UpstreamPathTemplate": "/review/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ]
        },

        {
          "DownstreamPathTemplate": "/api/profile/{everything}",
          "DownstreamScheme": "http",
          "ServiceName": "profile-service",
          "UpstreamPathTemplate": "/users/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityServerAuthentication",
            "AllowedScopes": []
          }
        }
      ],
      "GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
          "Port": 443,
          "Namespace": "default",
          "Type": "kube"
        }
      }
    }