apiVersion: v1
kind: ConfigMap
metadata:
  name: browsing-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:series-browsingdv.database.windows.net,1433;Initial Catalog=BrowsingDb;Persist Security Info=False;User ID=seriesDbLogin;Password=VeryStr0ngPass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:series-identitydb.database.windows.net,1433;Initial Catalog=IdentityDb;Persist Security Info=False;User ID=seriesDbLogin;Password=VeryStr0ngPass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:series-usersdb.database.windows.net,1433;Initial Catalog=usersDb;Persist Security Info=False;User ID=seriesDbLogin;Password=VeryStr0ngPass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: review-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:series-reviewdb.database.windows.net,1433;Initial Catalog=reviewDb;Persist Security Info=False;User ID=seriesDbLogin;Password=VeryStr0ngPass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: watching-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "DefaultConnection": "Server=tcp:series-watchingdb.database.windows.net,1433;Initial Catalog=watchingDb;Persist Security Info=False;User ID=seriesDbLogin;Password=VeryStr0ngPass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        },
        "RabbitMQConfig": {
            "Hostname": "messagebus-rabbitmq",
            "UserName": "user",
            "Port": 5672
        },
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  ocelot.json: |-
    {
    "ReRoutes": [
        {
        "DownstreamPathTemplate": "/api/series",
        "DownstreamScheme": "http",
        "UpstreamPathTemplate": "/series",
        "ServiceName": "browsing-service",
        "UpstreamHttpMethod": [ "Get" ]
        },

        {
        "DownstreamPathTemplate": "/api/series/{seriesId}",
        "DownstreamScheme": "http",
        "UpstreamPathTemplate": "/series/{seriesId}",
        "ServiceName": "browsing-service",
        "UpstreamHttpMethod": [ "Get" ]
        },

        {
        "DownstreamPathTemplate": "/api/series/categories",
        "DownstreamScheme": "http",
        "UpstreamPathTemplate": "/categories",
        "ServiceName": "browsing-service",
        "UpstreamHttpMethod": [ "Get" ]
        },

        {
        "DownstreamPathTemplate": "/api/artist",
        "DownstreamScheme": "http",
        "UpstreamPathTemplate": "/artists",
        "ServiceName": "browsing-service",
        "UpstreamHttpMethod": [ "Get" ]
        },

        {
          "DownstreamPathTemplate": "/api/profile/{userId}",
          "DownstreamScheme": "http",
          "UpstreamPathTemplate": "/users/{userId}",
          "ServiceName": "profile-service",
          "UpstreamHttpMethod": [ "Get" ],
          "AuthenticationOptions": {
              "AuthenticationProviderKey": "IdentityServerAuthentication",
              "AllowedScopes": []
          }
        },

        {
          "DownstreamPathTemplate": "/api/watching/{everything}",
          "DownstreamScheme": "http",
          "ServiceName": "watching-service",
          "UpstreamPathTemplate": "/watching/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          "AuthenticationOptions": {
              "AuthenticationProviderKey": "IdentityServerAuthentication",
              "AllowedScopes": []
          }
        }
    ],
    "GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
        "Port": 443,
        "Namespace": "default",
        "Type": "kube"
            }
        }
    }
