apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: identity-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: identity-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: identity-service
        image: identityimage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: messagebus-rabbitmq
              key: rabbitmq-password
        volumeMounts:
        - name: identity-config-volume
          mountPath: /app/config
      volumes:
      - name: identity-config-volume
        configMap:
          name: identity-config
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 4000
    targetPort: 80
  type: LoadBalancer