apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app.kubernetes.io/name: profile-service
    app.kubernetes.io/instance: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: profile-service
      app.kubernetes.io/instance: {{.Release.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profile-service
        app.kubernetes.io/instance: {{.Release.Name}}
    spec:
      containers:
        - name: profile-service
          image: seriestrackerregistry.azurecr.io/profileservice:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: IDENTITY_URL
              value: {{.Values.identity.url}}
          volumeMounts:
            - name: profile-config-volume
              mountPath: /app/config
      volumes:
        - name: profile-config-volume
          configMap:
            name: profile-config
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    app.kubernetes.io/name: profile-service
    app.kubernetes.io/instance: {{.Release.Name}}
spec:
  selector:
    app.kubernetes.io/name: profile-service
    app.kubernetes.io/instance: {{.Release.Name}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
